disabled_rules:
- trailing_whitespace
- identifier_name

excluded:
- Example
- Demo
- Carthage
- Pods
- .build

line_length:
  warning: 180
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
